### ISSUE TITLE
Additional Testcases for EMC Tests

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#46]
Suggested by esa: I would therefore recommend that you create software that exercise the operational capabilities on Astro Pi and CalliopEO in a tight controlled loop;
- On the Astro Pi mark II; just have a Python script running that will copy the same test program over to the CalliopEO repeatedly and record serial data being received from the CalliopEO to disk. This is basically the full extent of the Astro Pi involvement.
- The test program (hex file) should run on CalliopEO for maybe 15 seconds and rapidly read from each sensor and test every capability that will be used on orbit and transmit the result over serial to the Astro Pi (with a time stamp). Note the time stamp could be implemented on the Astro Pi side if you want.
- When the Astro Pi receives the finished message over serial from CalliopEO the whole process restarts with the Astro Pi copying the test program over again.

**Comment by rzbrk** [comment]
But I would propose to have to tests:
* Test that does not need intervention on ISS, like pressing buttons, verify that leds are on and the like
* Test testing ALL features including buttons and actuators

And these tests rely on having the CalliopEO hardware with e.g. the Grove sensors, right.

Could we use an existing hex available at Calliope as a starting point?

**Comment by rzbrk** [comment]
I created a new hex file for the 30s-iss-sensors testcase: https://github.com/rzbrk/30s-iss-sensors.

* As usual, the run time of the hex file can be configured via the variable `runMaxSeconds`.
* The update period/interval (how often the sensor values will be outputted via the serial port) can be configured via the variable `updatePeriod`.
* Some sensors can be excluded via boolean variables like `testSI1145`.
* The magnetometer of the Calliope is diabled, because I could not find out if I can skip the calibration

**Comment by rzbrk** [comment]
I added testing buttons to https://github.com/rzbrk/30s-iss-sensors.

Now, the magnetometer is still missing because of the problem with the calibration mentioned above.

I also saw, that the [Bosch BMX055](https://www.bosch-sensortec.com/products/motion-sensors/absolute-orientation-sensors/bmx055/) also incorporates a gyro. But this sensor data seems not to be accessible from Makecode.
