### ISSUE TITLE
Add shebang #!/usr/bin/env python3

### ISSUE THREAD

**Issue by rzbrk** [calliope-edu/CalliopEO_AstroPi#49]
Add shebang `#!/usr/bin/env python3` and make `chmod +x CalliopEO.py`. Then, the script can be executed with `./CalliopEO.py`.

**Comment by rzbrk** [comment]
See fix [5b84dbd](https://github.com/calliope-edu/CalliopEO_AstroPi/pull/50/commits/5b84dbdd4cef9de5faf720b266f22f9f78381d34).

Can be closed if #50 is merged.

**Comment by Amerlander** [comment]
shall we then add `chmod +x ./CalliopEO.py` in the setup script?

**Comment by rzbrk** [comment]
Do we really need this? The permissions are usually also stored in the repo. For example, this works in my case for setup.sh and testing.sh. Do you have to set the executable flag for every file?

**Comment by Amerlander** [comment]
I have to do this for the .sh files. The .py script executes with `python3 CalliopEO.py`  without having `chmod +x`. So I have to do this for the setup script and then for the testfile (where I think it is okay do do not have this executeable by default)

But I download the Zip file, unpack it localy and then upload everything via ssh. I'll test what happens when I upload the Zip and unpack it on the pi.

**Comment by Amerlander** [comment]
The test files itself run without being executeable

**Comment by rzbrk** [comment]
yes, the testcase files do not need the executable flag, only testing.sh in the main directory.

maybe, by copying the individual files via ssh the flag gets lost. but zip also stores them.

**Comment by Amerlander** [comment]
yes, using the zip works without chmoding anything
