### ISSUE TITLE
Handle SSH timeout

### ISSUE THREAD

**Issue by Amerlander** [calliope-edu/CalliopEO_AstroPi#62]
Should we provide a best practice to prevent script exit caused by ssh timeout or isn't that in our scope?
I just tried some longer scripts and got around with `nohup`

**Comment by rzbrk** [comment]
Disconnections can happen when communicating with ISS because of Loss of Contact events (LOCs). I would expect, BIOTESC will handle this properly, e.g. by using a terminal multiplexer like screen or tmux. In case of a disconnection because of LOC, one can resume the terminal session at a later point in time.

**Comment by rzbrk** [comment]
Can be closed if PR is merged.
